name: Build Persona 5 Royal Luma

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Persona 5 Royal x64 Release
      run: |
        msbuild "Source/Games/Persona 5 Royal/Persona 5 Royal.vcxproj" /p:Configuration="Publishing-Release" /p:Platform="x64" /p:DefineConstants="REMOTE_BUILD=1"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Luma-Persona_5_Royal
        path: |
          Source/Games/Persona 5 Royal/Binaries/x64-Publishing-Release/
          Source/Games/Persona 5 Royal/Binaries/
        if-no-files-found: error
