name: Build Persona 5 Royal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Persona 5 Royal x64 Publishing-Release
        run: |
          msbuild "Source/Games/Persona 5 Royal/Persona 5 Royal.vcxproj" `
            /p:Configuration="Publishing-Release" `
            /p:Platform="x64" `
            /p:DefineConstants="REMOTE_BUILD=1"

      - name: Upload Persona 5 Royal addon
        uses: actions/upload-artifact@v4
        with:
          name: Luma-Persona5-Royal-Build
          path: |
            Source/Games/Persona 5 Royal/Binaries/x64-Publishing-Release/*.addon
          if-no-files-found: error
